# Generated by Django 5.2.3 on 2025-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=255)),
                ('lieux', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('date_evenement', models.DateField()),
                ('forfait', models.CharField(max_length=100)),
            ],
        ),
    ]
